name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Matrix to run on both Ubuntu and Windows

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build for release
      run: dotnet publish -c Release -r win-x64 --self-contained false --output ./publish
    - name: Create GitHub release
      id: create_release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Timestamp tag
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        gh release create $TAG_NAME ./publish/* --title "Release $TAG_NAME" --notes "Release with timestamp tag"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
